### ISSUE TITLE
Some remarks from ChromeXt

### ISSUE THREAD

**Issue by JingMatrix** [fishjar/kiss-translator#4]
Hello, I am the author of [ChromeXt](https://github.com/JingMatrix/ChromeXt).
Today, I changed ChromeXt to support your userscript beacuse of https://github.com/JingMatrix/ChromeXt/issues/92 .

While I was debugging,  I had some advices might be helpful for you to improve your work:
1. A typo, it should be `GM.xmlHttpRequest` - note H is uppercase (see https://violentmonkey.github.io/api/gm/)
2. `GM` is not necessarily defined as a property of `window`, it is better to use `GM.setValue` instead of `window.GM.setValue`
3. The same for `unsafeWindow`, it is better use `unsafeWindow` instead of `window.unsafeWindow`

There are just my personal opinions. Without changing them, ChromeXt can still run it.
Above all, I appreciate your work.

**Comment by fishjar** [comment]
Thank you for your kind reminder, in fact this is my first time developing a greasemonkey script and I really need similar advice and help.

The alias of `GM_xmlhttpRequest` is `GM.xmlHttpRequest` which really confuses me, the spelling is not uniform.
What confuses me even more is why `XMLHttpRequest` is used instead of the more modern `fetch` interface.

Anyway, I have modified and simplified my code according to your suggestion, see this [commit](https://github.com/fishjar/kiss-translator/commit/f1f15c7eb129176ceda16db9f2d52b9125b7956f) for details.

**Comment by JingMatrix** [comment]
For me, I need to implement `GM_xmlhttpRequest` using Android Java natively (since I have no access to the browser process).
From Java side, there is no advantage of using Fetch API.
Moreover, the `Request` class is confusing, it is not known whether the body data is text or binary.
Of course, from JS side, `Fetch` is more user-friendly.
